---
- hosts: tomcatservers
environment:
    JAVA_HOME: "C:\\Program Files\\Java\\jdk-21"
  vars:
  - warName: java-example.war
  - warRemotePath: C:\Users\Hp\Downloads\apache-tomcat-9.0.87-windows-x64\apache-tomcat-9.0.87

  tasks:
  - name: Copy WAR to Remote server
    copy: src=target/{{ warName }} dest={{ warRemotePath }}/{{ warName }} owner=tomcat group=tomcat
   
